[phases.setup]
aptPkgs = [
  "libjpeg-dev", "libpng-dev", "libwebp-dev", "zlib1g-dev",
  "libtiff5-dev", "libfreetype6-dev", "liblcms2-dev",
  "libopenjp2-7-dev", "libimagequant-dev", "libxcb1-dev"
]

[phases.build]
cmds = ["pip install --no-cache-dir --no-build-isolation -r requirements.txt"]
